### PR TITLE
POJO classes

### PR DESCRIPTION
**Pull request by ViachaslauPratasenia**

### CODE REVIEW

**Review by NasterVill — APPROVED** [review]
All the fields seem to be there. Can be merged!

**Review by NasterVill — CHANGES_REQUESTED** [review]
Remove separate location fileds from profile and use general loccation model

**Review by NasterVill — APPROVED** [review]

**Review by NasterVill — APPROVED** [review]
Seems to be a okay. Can be merged

**Comment by valerycadovic** [comment]
Contacts retrieving model is okay.

**Review by NasterVill — APPROVED** [review]
Meets the rules. Can be merged

**Pull request merged**
